---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: academy
  label: academy
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/english/blog
  label: Post
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/english/author
  label: Author
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: exampleSite/content/english/course
  label: Course
  create: documents
  match: "**/*"
  templates:
  - course
- type: directory
  path: exampleSite/content/english/notice
  label: Notice
  create: all
  match: "**/*"
  templates:
  - notice
- type: directory
  path: exampleSite/content/english/teacher
  label: Teacher
  create: all
  match: "**/*"
  templates:
  - teacher
- type: directory
  path: exampleSite/content/english/event
  label: Event
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: exampleSite/content/english/research
  label: Research
  create: all
  match: "**/*"
  templates:
  - research
- type: directory
  path: exampleSite/content/english/scholarship
  label: Scholarship
  create: all
  match: "**/*"
  templates:
  - scholarship
- type: directory
  path: exampleSite/content/english/about
  label: About
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/contact
  label: Contact
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/pages
  label: Created Pages
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/english
  label: All Pages
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/data/en
  label: Data
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
